[package]
name = "rust-kintone"
version = "0.1.0"
authors = ["Toru Kobayashi <koba0004@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "kintone"
path = "src/lib.rs"

[dependencies]
